version: '2'

services:

  ### Start httpd service from container and share ~/public_http.
  llaumgui_centos7-scl-httpd24:
    container_name: llaumgui_centos7-scl-httpd24
    image: llaumgui/centos7-scl-httpd24
    build: 
      context: ../docker-images/httpd/2.4/
    restart: always
    mem_limit: 512m
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ~/public_html:/var/www/html
     - ./volumes/conf/httpd24/vhost.d:/etc/httpd/vhost.d:ro
     - ./volumes/log/httpd24:/var/log/httpd24
    ports:
     - 80:80
    links:
     - llaumgui_centos7-scl-php56:php56

  ### Start php-fpm service from container.
  llaumgui_centos7-scl-php56:
    container_name: llaumgui_centos7-scl-php56
    image: llaumgui/centos7-scl-php56
    build: 
      context: ../docker-images/php-fpm/5.6/
    restart: always
    mem_limit: 1g
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ~/public_html:/var/www/html
     - ./volumes/conf/php56/90-custom.ini:/etc/php.d/90-custom.ini:ro
     - ./volumes/log/php56:/var/log/php-fpm
    expose:
     - 9000
    links:
     - mariadb10:container_database
     - memcached:container_memcached
     - llaumgui_centos7-sphinxse:container_sphinx

  ### Start SphinxSE service from container.
  llaumgui_centos7-sphinxse:
    container_name: llaumgui_centos7-sphinxse
    image: llaumgui/centos7-sphinxse
    build: 
      context: ../docker-images/sphinxse/2/
    restart: always
    mem_limit: 1g
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/data/sphinxse:/var/lib/sphinx
      - ./volumes/conf/sphinxse:/etc/sphinx:ro
      - ./volumes/log/sphinxse:/var/log/sphinx
    expose:
     - 9312
    links:
     - mariadb10:container_database

  ### Start mariadb service from container.
  mariadb10:
    container_name: mariadb10
    image: mariadb:10
    restart: always
    mem_limit: 1g
    env_file:
      - .env
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./volumes/data/mysql:/var/lib/mysql
    ports:
     - 3306:3306

  # Start memcached service from container.
  memcached:
    container_name: memcached
    image: memcached
    mem_limit: 256m
    volumes:
     - /etc/localtime:/etc/localtime:ro
    expose:
     - 11211
