version: '2'

services:

  ### Start httpd service from container and share ~/public_http.
  jeedom:
    container_name: jeedom
    image: jeedom/jeedom
    restart: always
    mem_limit: 1g
    privileged: true
    volumes:
     - /etc/localtime:/etc/localtime:ro
    # - /dev/tty*:/dev
     - ./volumes/data/jeedom:/var/www/html
    ports:
     - 80:80
    links:
     - mariadb10:container_database

  ### Start mariadb service from container.
  mariadb10:
    container_name: mariadb10
    image: mariadb:10
    restart: always
    mem_limit: 1g
    env_file:
      - .env
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./volumes/data/mysql:/var/lib/mysql
    ports:
     - 3306:3306