# Start httpd service from container and share ~/public_http.
httpd24:
  #container_name: llaumgui_centos-scl-httpd24
  build: build/httpd/2.4
  #image: llaumgui/centos-httpd24
  ports:
   - "80:80"
  volumes:
   - ~/public_html:/var/www/html
   - ./conf/httpd24/vhost.d:/etc/httpd/vhost.d
   - ./log/httpd24:/var/log/httpd24
  links:
   - php56fpm


# Start php-fpm service from container.
php56fpm:
  #container_name: llaumgui_centos-scl-php56-fpm
  build: build/php-fpm/5.6
  #image: llaumgui/centos-php56
  ports:
   - "9000:9000"
  volumes:
   - ~/public_html:/var/www/html
   - ./conf/php56/90-custom.ini:/etc/php.d/90-custom.ini
   - ./log/php56:/var/log/php-fpm
  stdin_open: true
  links:
   - mariadb10
   - memcached
#   - sphinxse


# Start SphinxSE service from container.
#sphinxse:
#  #container_name: llaumgui_centos-sphinxse
#  build: build/sphinxse/2
#  ports:
#   - "9312:9312"


# Start mariadb service from container.
mariadb10:
  #container_name: llaumgui_mariadb
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: docker
  ports:
   - "3306:3306"
  volumes:
   - ./data/mysql:/var/lib/mysql


# Start memcached service from container.
memcached:
  #container_name: llaumgui_memcached
  image: memcached
  ports:
   - "11211:11211"